services:

  postgres:
    image: postgres:16-alpine
    pids_limit: -1
    container_name: propvest_postgres
    environment:
      POSTGRES_USER: propvest
      POSTGRES_PASSWORD: password
      POSTGRES_DB: propvest
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U propvest -d propvest"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: propvest_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: propvest_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: propvest
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: propvest-backend:latest
    container_name: propvest_api
    env_file:
      - .env
    ports:
      - "8081:8081"
    command: ["./api"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: propvest-backend:latest
    container_name: propvest_worker
    env_file:
      - .env
    command: ["./worker"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  rabbitmq_data: